### ISSUE TITLE
System tray icon for Gnome Shell

### ISSUE THREAD

**Issue by conspacer** [netblue30/firetools#25]
Is it possible to change the system tray icon? It is a little bit gaudy and loud for my taste. It would be nice to have it in B&W that matches with the Gnome Shell experience.
![firetoolsicon](https://user-images.githubusercontent.com/23648459/29355540-bf22948e-8271-11e7-8022-8386b51b5ea4.png)

**Comment by d2s** [comment]
I made a grayscale version of the application's icon.

![firetools-minimal](https://user-images.githubusercontent.com/135053/34632362-9ee542d0-f27d-11e7-8369-b90604787a0b.png)

Switching to this requires several changes to the manifest and build tasks,
etc. so that it will get included to the built software package.

At the moment of writing, currently working on cleaning up the UI of the app launcher
(from the red color to a lot more peaceful dark grayscale color palette).

**Comment by netblue30** [comment]
Closing for now, thanks for the fix!
