### ISSUE TITLE
Slight Cosmetic & Convenience Issues

### ISSUE THREAD

**Issue by bitnom** [netblue30/firetools#5]
The functionality of Firetools is great but the width of the GUI is very wide in comparison to the icons within. I also don't get the black grid. Also, it would be nice if it were a tray icon rather than in the task bar. Some theming options would be nice. Otherwise, it works fine. Was just hoping you might have these sorts of changes on the roadmap.

**Comment by netblue30** [comment]
Can you take some screenshots and attach them here in a comment, I'll try to fix them. Thanks.

**Comment by AVJoKe** [comment]
This might not be directly related to this issue, but I couldn't find your email.

At the moment I'm writing my own GUI since I can't use yours. The design is not usable for me, some of the code in it looks terrible and is missing several features I would like to have. The current state of my GUI is pretty basic and mostly shows the found profiles, open them with the default editor of the system and offer the option to start/stop them. Currently I'm working on a option to quickly edit parameters of a config and save them separated. I would like to know if you're interested in this? 
Sorry for the harsh comment, I really enjoy firejail but the GUI is just not ok for me. It's not on github yet but I'm gonna push it soon.

Regards,

**Comment by netblue30** [comment]
Yes, if you get something going I'll merge you in. Thanks!

**Comment by startx2017** [comment]
This looks like it was merged, I'll close it. Thanks.
