### ISSUE TITLE
How to use u2f key in a firetools browser?

### ISSUE THREAD

**Issue by ghost** [netblue30/firetools#56]
I installed YubiKey 5 NFC on my Linux Mint  
in this way .
Q: How can I setup my Linux instance for use with U2F? 
https://www.yubico.com/authentication-standards/fido-u2f/#toggle-id-9 

Yubikey (with U2F) works well in Firefox.
But does not work in Firetools Firefox.
https://firejailtools.wordpress.com/screenshots/  

How do I install Yubikey (with U2F) in Firetools Firefox ?

I'm not experienced. please explain with images.

**Comment by rusty-snake** [comment]
Set `browser-disable-u2f no` in `/etc/firejail/firejail.config`, you can do this with `sudo sed -i "s/# browser-disable-u2f yes/browser-disable-u2f no/g" /etc/firejail/firejail.config` or by running [firejail-welcom.sh](https://github.com/netblue30/firejail/blob/master/contrib/firejail-welcome.sh) (e.g. `curl "https://raw.githubusercontent.com/netblue30/firejail/master/contrib/firejail-welcome.sh" | bash`).

**Comment by chantal43** [comment]
Thank you but it doesn't work. 
When I try to set     # browser-disable-u2f no      in       /etc/firejail/firejail.config   
I get to see this "is only reading" 

https://ibb.co/QpK37B0

and when I press replace I get to see this . "Could not save the file  /etc/firejail/firejail.config ".

https://ibb.co/x6CmvcY 

I tried  in Terminal       sudo sed -i "s/# browser-disable-u2f yes/browser-disable-u2f no/g" /etc/firejail/firejail.config        

But nothing happened. it doesn't work .

firejail-welcom.sh   I don't understand . 

(Sorry about disk errors. I use a translater because my english is not so good .)

**Comment by chantal43** [comment]
Forget my last answer. I seem to have done something wrong. 
It's working now. Thank you so much.

**Comment by ghost** [comment]
It's working. 
Thank you so much.

**Comment by rusty-snake** [comment]
FWIW: `sudo sed -i "s/# browser-disable-u2f yes/browser-disable-u2f no/g" /etc/firejail/firejail.config` shows nothing (expect for the password prompt) if it does not encounter any errors.

**Comment by ghost** [comment]
Yes 
sudo sed -i "s/# browser-disable-u2f yes/browser-disable-u2f no/g" /etc/firejail/firejail.config     
Works  
Thank you so much.
